version: "3"

services:
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            default:
                ipv4_address: 192.168.0.2

networks:
    default:
        driver: bridge
        ipam:
            config:
                -   subnet: 192.168.0.0/24
                    gateway: 192.168.0.1